"""How brittle is the reported policy to dynamics it never trained on?

Evaluates the already-trained FetchPush seeds under systematically shifted
block mass and sliding friction, using the exact R4 protocol (50 episodes,
eval seeds 10000+, deterministic policy) with only the simulator's physical
parameters changed.

This needs no new training, and it answers the question that decides
whether domain-randomized training is worth running at all: if the nominal
policy already survives 2x friction, DR has nothing to recover.

Usage: uv run python scripts/dynamics_sweep.py
Writes results/dynamics_sweep.md.

A cross, not a full grid: mass is swept at nominal friction and friction at
nominal mass. A full grid costs quadratically for a second-order
interaction we have no reason to expect and could not resolve at 3 seeds.
"""

import argparse
from pathlib import Path

import gymnasium as gym
import gymnasium_robotics  # noqa: F401  (registers Fetch env IDs)
import numpy as np

from src.agent.evaluate import evaluate, load_policy
from src.envs.domain_randomization import FixedDynamics

ENV_ID = "FetchPush-v4"
RUNS = ["push_td3_her_seed0", "push_td3_her_seed1", "push_td3_her_seed2"]
# Multipliers on the stock value; 1.0 is the reported condition and is
# included so the sweep reproduces the headline number as its own control.
# Finer below 0.5x: a 10-episode pilot put the failure boundary between
# 0.25x (0.067) and 0.5x (0.867), and where a policy breaks is more
# informative than another point in the region where it does not.
MASS_MULTS = [0.2, 0.25, 0.3, 0.4, 0.5, 1.0, 2.0, 4.0, 8.0]
FRICTION_MULTS = [0.1, 0.25, 0.5, 1.0, 2.0, 4.0]


def eval_at(policy_fn, mass_mult: float, friction_mult: float, episodes: int) -> float:
    res = evaluate(
        policy_fn, ENV_ID, episodes, 10_000,
        make_env=lambda: FixedDynamics(
            gym.make(ENV_ID), mass_mult=mass_mult, friction_mult=friction_mult
        ),
    )
    return float(res["success_rate"])


def sweep_axis(policies, axis: str, mults, episodes):
    """rows of (multiplier, [per-seed success], mean, std)."""
    out = []
    for m in mults:
        per_seed = [
            eval_at(p, m if axis == "mass" else 1.0, m if axis == "friction" else 1.0,
                    episodes)
            for p in policies
        ]
        out.append((m, per_seed, float(np.mean(per_seed)), float(np.std(per_seed))))
        print(f"  {axis} x{m:<5} {np.mean(per_seed):.3f} ± {np.std(per_seed):.3f}"
              f"  {[f'{v:.2f}' for v in per_seed]}")
    return out


def table(rows, axis: str, nominal: float) -> list[str]:
    lines = [
        f"| {axis} multiplier | Success (mean ± std, 3 seeds) | Per-seed | vs nominal |",
        "|---|---|---|---|",
    ]
    for m, per_seed, mean, std in rows:
        tag = " *(reported condition)*" if m == 1.0 else ""
        delta = "—" if m == 1.0 else f"{mean - nominal:+.3f}"
        lines.append(
            f"| ×{m}{tag} | {mean:.3f} ± {std:.3f} | "
            f"{', '.join(f'{v:.2f}' for v in per_seed)} | {delta} |"
        )
    return lines


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--results-dir", default="results")
    parser.add_argument("--episodes", type=int, default=50)
    args = parser.parse_args()
    res = Path(args.results_dir)

    missing = [r for r in RUNS if not (res / r / "checkpoint_best.pt").exists()]
    if missing:
        raise SystemExit(f"missing checkpoints: {missing}")
    policies = [load_policy(res / r / "checkpoint_best.pt", ENV_ID) for r in RUNS]

    print("mass sweep (friction nominal):")
    mass_rows = sweep_axis(policies, "mass", MASS_MULTS, args.episodes)
    print("friction sweep (mass nominal):")
    fric_rows = sweep_axis(policies, "friction", FRICTION_MULTS, args.episodes)

    nominal = next(mean for m, _, mean, _ in mass_rows if m == 1.0)
    nominal_f = next(mean for m, _, mean, _ in fric_rows if m == 1.0)
    assert abs(nominal - nominal_f) < 1e-9, (
        "the two sweeps disagree at ×1.0, which should be the identical "
        "condition — something is leaking between evaluations"
    )

    lines = [
        "# Robustness to dynamics the policy never trained on",
        "",
        "The reported FetchPush policies (3 seeds, trained on stock dynamics "
        "only) evaluated under shifted block mass and sliding friction. Exact "
        f"R4 protocol — {args.episodes} episodes, eval seeds 10000+, "
        "deterministic policy — with only the simulator's physical parameters "
        "changed. Generated by `scripts/dynamics_sweep.py`.",
        "",
        "×1.0 is the reported condition and is included as the sweep's own "
        f"control: it reproduces the headline {nominal:.3f}.",
        "",
        "## Block mass",
        "",
        *table(mass_rows, "Mass", nominal),
        "",
        "## Sliding friction",
        "",
        *table(fric_rows, "Friction", nominal),
        "",
        "No domain randomization was used in training. This measures the "
        "*unaided* robustness of the reported agent, and is the baseline any "
        "domain-randomized variant would have to beat.",
        "",
    ]
    out = res / "dynamics_sweep.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
