"""Generate the single-factor stabilizer ablation configs.

docs/writeup.md section 5 states plainly that we changed five settings at
once and cannot apportion credit inside the package. This generates the
experiment that closes that gap: five configs, each identical to the
reported one except that ONE stabilizer is reverted.

The reverted value is read from TrainConfig's dataclass defaults rather
than typed here, because those defaults *are* the failed campaign's
settings — so "reverted" provably means "back to what did not learn", and
this script cannot drift from the code the way a hand-written YAML would.

Usage: uv run python scripts/make_ablation_configs.py
Writes configs/td3_her_push_ablate_<key>.yaml (5 files).
"""

import argparse
import dataclasses
from pathlib import Path

import yaml

from src.agent.train import TrainConfig

BASE = Path("configs/td3_her_push.yaml")

# The five deviations from docs/writeup.md section 2 / results/config_diff.md.
# Each must be a key whose reported value differs from the TrainConfig
# default; that invariant is asserted below rather than assumed.
STABILIZERS = ["action_l2", "normalize_obs", "tau", "expl_noise", "random_eps"]

HEADER = """\
# GENERATED by scripts/make_ablation_configs.py -- do not edit by hand.
#
# Single-factor ablation of the stabilizer package (docs/writeup.md section 5).
# Identical to configs/td3_her_push.yaml except `{key}`, reverted to the
# TrainConfig default ({old!r} -> {new!r}), which is the value the first
# FetchPush campaign failed under.
#
# If this run still solves the task, `{key}` was not load-bearing.
"""


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--base", default=str(BASE))
    parser.add_argument("--out-dir", default="configs")
    args = parser.parse_args()

    base_path = Path(args.base)
    base = yaml.safe_load(base_path.read_text())
    defaults = {f.name: f.default for f in dataclasses.fields(TrainConfig)}

    written = []
    for key in STABILIZERS:
        assert key in base, f"{base_path} does not set `{key}`"
        assert key in defaults, f"TrainConfig has no field `{key}`"
        reported, reverted = base[key], defaults[key]
        assert reported != reverted, (
            f"`{key}` is already at its TrainConfig default ({reverted!r}) in "
            f"{base_path} — there is nothing to ablate, so the write-up's "
            "five-deviation claim and this script disagree"
        )

        cfg = dict(base)
        cfg[key] = reverted
        cfg["run_dir"] = f"results/ablate_{key}"

        out = Path(args.out_dir) / f"td3_her_push_ablate_{key}.yaml"
        out.write_text(
            HEADER.format(key=key, old=reported, new=reverted)
            + yaml.safe_dump(cfg, sort_keys=True, default_flow_style=False)
        )

        # The whole point is a *single* factor. run_dir differs by design.
        delta = {k for k in set(base) | set(cfg) if base.get(k) != cfg.get(k)}
        assert delta == {key, "run_dir"}, (
            f"{out} differs from the base in {sorted(delta)}, not just `{key}`"
        )
        written.append((out, key, reported, reverted))

    print(f"wrote {len(written)} configs (base: {base_path})\n")
    print(f"{'config':52} {'reverted key':16} change")
    for out, key, old, new in written:
        print(f"{str(out):52} {key:16} {old!r} -> {new!r}")
    print(
        "\nEach is a one-key delta from the reported config; the reverted value "
        "is TrainConfig's default, i.e. the failed campaign's setting."
    )


if __name__ == "__main__":
    main()
